# Generated by Django 2.0.1 on 2019-08-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20190827_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitimageentty',
            name='url',
            field=models.ImageField(max_length=50, upload_to='fruit', verbose_name='地址'),
        ),
    ]
