# Generated by Django 2.0.1 on 2019-08-31 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20190831_1008'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userentity',
            managers=[
            ],
        ),
    ]
