# Generated by Django 2.0.1 on 2019-08-28 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_fruitcartentity'),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=20, null=True, verbose_name='收货人')),
                ('receiver_phone', models.CharField(max_length=11, null=True, verbose_name='收货人电话')),
                ('receiver_address', models.TextField(verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '用户地址表',
                'verbose_name_plural': '用户地址表',
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cnt', models.IntegerField(default=0, verbose_name='数量')),
                ('pay_type', models.IntegerField(choices=[(0, '余额'), (1, '银行卡'), (2, '微信支付'), (3, '支付宝')], default=0, verbose_name='支付方式')),
                ('pay_status', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '待收货'), (3, '已收货'), (4, '完成'), (5, '取消')], default=0, verbose_name='订单状态')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.FruitEntity', verbose_name='水果')),
            ],
            options={
                'verbose_name': '订单详情表',
                'verbose_name_plural': '订单详情表',
                'db_table': 't_detail',
            },
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='last_time',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pay_status',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver_address',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='receiver_phone',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='用户id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderAddress', verbose_name='地址id'),
            preserve_default=False,
        ),
    ]
