# Generated by Django 2.0.1 on 2019-08-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_fruitcartentity'),
        ('orderapp', '0002_auto_20190828_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='用户id'),
            preserve_default=False,
        ),
    ]
