# Generated by Django 2.0.1 on 2019-08-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0003_orderaddress_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.UserEntity', verbose_name='用户名称'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderModel', verbose_name='订单名称'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.OrderAddress', verbose_name='收货地址'),
        ),
    ]
